version : '3'

services:

  redis:
    image: redis:alpine
    container_name: redis

  db: 
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-container
    ports: 
      - 8000:8000
    restart: on-failure
    depends_on:
      - db
    
  celery:
    restart: always
    build:
      context: .
    command: celery -A MyFirstProject worker -l DEBUG
    volumes:
      - .:/app
    container_name: celery
    depends_on:
      - db
      - redis
      - web

  

  

   # image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # container_name: postgres_db


